#!/bin/bash

# SETTINGS
MKCERT="mkcert" # path to mkcert binary
CERT_FOLDER="$HOME/.serveit-certs" # path to certificate folder

# check parameters
[ $# -ne 3 ] && echo "usage: serveit <domain> <server port> <stunnel port>" && exit

# check that mkcert binary is found
[ ! -x $(which $MKCERT) ] && echo "mkcert binary not found" && exit

# create certificate folder if it does not exist
[ ! -d $CERT_FOLDER ] && mkdir $CERT_FOLDER
[ ! -d $CERT_FOLDER ] && echo "Unable to create certificate folder" && exit

# check if script was run as sudo
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo"
    exit 1
fi

# get current user
username=$(logname)

# install certificate
sudo su - "$username" -c "$MKCERT -key-file $CERT_FOLDER/$1-key.pem -cert-file $CERT_FOLDER/$1-cert.pem $1"

# create bundled certificate for stunnel
cat $CERT_FOLDER/$1-key.pem $CERT_FOLDER/$1-cert.pem > $CERT_FOLDER/$1-bundle.pem

# set permissions for certificates
chmod 600 $CERT_FOLDER/$1-bundle.pem $CERT_FOLDER/$1-key.pem $CERT_FOLDER/$1-cert.pem

# add domain to /etc/hosts
echo "# added by serveit" >> /etc/hosts
echo "127.0.0.1 $1" >> /etc/hosts

# start PHP built in server
php -S $1:$2 &

# start stunnel
stunnel3 -f -d $3 -r $2 -p $CERT_FOLDER/$1-bundle.pem &

sleep 1
echo ""
echo "## Your local SSL site is now available at https://$1:$3"

# function to stop both servers
cleanup() {
    echo ""
    echo "Removing /etc/hosts entry..."
    sudo sed -i -e "/# added by serveit/,/127.0.0.1 $1/d" /etc/hosts

    echo "Killing PHP and stunnel"
    sudo kill $(jobs -p)

    echo ""
    echo "Killed servers."
}

# trap Ctrl+C signal and call cleanup function
trap cleanup INT

# wait for both servers to finish
wait
